export use commands.nu [
    # "alignit"
    # "history-backup"
    "bar"
    "bye"
    # "cb"
    "center"
    # "git-check-file-clean"
    # "colorit"
    "copy-cmd"
    "cprint"
    "cd-root"
    # "dedent"
    # "download-nushell-nightly"
    # "escape-nushell-escapes"
    # "escape-regex"
    "example"
    "fs"
    "fill non-exist"
    "find-root"
    "figlet-demo"
    "format profile"
    # "frameit"
    "gradient-screen"
    "ls-git-modified-date"
    "hist"
    "hist-to-script"
    "in-fx"
    "in-hx"
    # "in-vd history"
    "in-vd"
    # "indent"
    # "indentit"
    "L"
    "llm message"
    # "launch-downloaded"
    "ln-for-preview"
    "mc"
    "md"
    "mv1"
    "mygit log"
    # "newlineit"
    "normalize"
    # "nu-completions-cwds"
    "nu-format"
    "nu-test install"
    "nu-test launch"
    "number-col-format"
    "number-format"
    "O"
    "orbita"
    "print-and-pass"
    "ramdisk-create"
    # "remove_single_nls"
    "replace-in-all-files"
    "rename-tab"
    "select-i"
    "side-by-side"
    # "significant-digits"
    # "str append"
    "str c"
    # "str prepend"
    # "str repeat"
    # "testcd"
    "to-safe-filename"
    "to-temp-file"
    "transcribe"
    "wez-to-asciicast"
    "wez-to-ansi"
    "wez-to-gif"
    "wez-to-png"
    # "width-safe"
    # "wrapit"
    "z"
]

export use update-public-git.nu
